config/routes.rb
Rails.application.routes.draw do
  get '/entries', to: "user_entries#index"
  get '/new_entry', to: "user_entries#new"
  post '/entries', to: "user_entries#create"

  devise_for :users 

  resources :categories do
    resources :entries
  end

  root 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user
    has_many :entries, dependent: :destroy
    validates :title, presence: true, length: {maximum: 17}
end

app/models/entry.rb
class Entry < ApplicationRecord
    belongs_to :category
    validates :title, presence: true, length: {maximum: 50}
    has_rich_text :body
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :entries, through: :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index
    # Firm#clients (similar to Client.where(firm_id: id))
    @categories = current_user.categories
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = current_user.categories.build
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = current_user.categories.build(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # Limit access of user to his own categories
    def set_category
      @category = current_user.categories.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_category
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  def index
    # Firm#clients (similar to Client.where(firm_id: id))
    @entries = @category.entries
    # @entries = current_user.entries
  end

  # GET /entries/1
  def show
  end

  # GET /entries/new
  def new
    @entry = @category.entries.build
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  def create
    #Firm#clients.build
    @entry = @category.entries.build(entry_params)

    if @entry.save
      redirect_to category_entries_path(@category), notice: 'Entry was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /entries/1
  def update
    if @entry.update(entry_params)
      redirect_to category_entry_path(@category), notice: 'Entry was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /entries/1
  def destroy
    @entry.destroy
    redirect_to category_entries_path(@category), notice: 'Entry was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = @category.entries.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:title, :body, :date)
    end

    def set_category
      @category = current_user.categories.find(params[:category_id])
    end
end

app/controllers/user_entries_controller.rb
class UserEntriesController < ApplicationController
  before_action :check_categories, only: [:new, :create]
  def index
    # cate = params[:cate]
    #   if !cate.nil?
    #     @entries = Entry.where(:category_id => cate)
    #   else
    #     @entries = current_user.entries
    #   end

    day = params[:day]
    if !day.nil?
      @entries = current_user.entries.where(:date => day)
    else
      @entries = current_user.entries
    end
  end

  def new
    @entry = current_user.entries.build
  end

  def create
    #Firm#clients.build
    @entry = current_user.entries.build(entry_params)

    if @entry.save
      redirect_to entries_path, notice: 'Entry was successfully created.'
    else
      render :new
    end
  end

  private

    # Only allow a list of trusted parameters through.
  def entry_params
    params.require(:entry).permit(:title, :body, :date, :category_id)
  end

  def check_categories
    if current_user.categories.any?
      return
    else
      redirect_to new_category_path, notice: "Please create a category first."
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def format_date(date)
        
    end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/categories/_dropdown.html.erb
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Categories
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <% @categories.each do |category| %>
        <li><%= link_to category.title, category, :class => "dropdown-item"%></li>
        <% end %>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Add New Category</a></li>
    </ul>
</li>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>

  <% if category.errors.any? %>

    <% category.errors.each do |error| %>

      <div class="container">
        <div class="alert alert-danger alert-dismissible fade show mx-auto col-10 text-center mb-1 mt-4" role="alert">
          <%= error.full_message %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      </div>
    
    <% end %>
  <% end %>

  <div class ="container">
    <section class = "col-8 mx-auto">
      <div class = "card rounded-3 mt-5">
        <div class="card-body p-4 p-sm-5">

          <div class="field form-group mb-3">
            <%= form.label :title %>
            <%= form.text_field :title, :class => "form-control" %>
          </div>

          <div class="actions d-grid mb-3 mt-4">
            <%= form.submit :class => "btn btn-primary btn-login text-uppercase fw-bold"%>
          </div>

        </div>
      </div>
    </section>
  </div>

<% end %>

app/views/categories/edit.html.erb
<%= render 'form', category: @category %>

<div class ="container mt-3">
    <section class = "col-8 mx-auto">
        <%= link_to "← #{@category.title}", @category, :class => "btn btn-outline-dark btn-sm mb-4" %> 
        <%= link_to '← Categories', categories_path, :class => "btn btn-outline-dark btn-sm mb-4" %>
    </section>
</div>

app/views/categories/index.html.erb
<div class = "container">
  <h1 class = "mt-4">Categories</h1>
  <section class = "row row-cols-1 row-cols-md-3 row-cols-sm-2 row-cols-lg-4 g-4">

    <% @categories.each do |category| %>
      
      <div class = "col">

        <div class="card h-100 w-100 my-3">

          <h5 class="card-header"><%= link_to category.title, category, :class => "remove-link-underline"%></h5>
          <div class="card-body d-flex flex-column justify-content-between">
            <p class="card-text"><small><i class="bi bi-pin-fill"></i> entries: <%= category.entries.count %></small></p>
            <p class="card-subtitle mb-2 text-muted small"><i class="bi bi-arrow-repeat"></i> last updated: <%= category.entries.last.updated_at.strftime('%b %e, %Y') %></p>
          </div>
          <div class = "list-group d-flex flex-row justify-content-between">
            <%= link_to '', new_category_entry_path(category), :class => "bi bi-plus-square list-group-item-action d-flex justify-content-center py-2 align-items-center remove-link-underline" %>
            <%= link_to '', category, :class => "bi bi-arrows-fullscreen list-group-item-action d-flex justify-content-center py-2 align-items-center remove-link-underline"%>
            <%= link_to '', edit_category_path(category), :class => "bi bi-pencil-square list-group-item-action d-flex justify-content-center py-2 align-items-center remove-link-underline" %>
            <%= link_to '', category, method: :delete, data: { confirm: 'Are you sure?' }, :class => "bi bi-trash-fill list-group-item-action d-flex justify-content-center py-2 align-items-center remove-link-underline" %>
          </div>

        </div>

      </div>

    <% end %>

    <div class ="col">
      <div class="card h-100 w-100 my-3 ratio ratio-4x3">
        <%= link_to '+', new_category_path, :class => "remove-link-underline display-4 text-secondary card-body list-group-item-action d-flex align-items-center justify-content-center"%>
      </div>
    </div>


  </section>
</div>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>

<div class ="container mt-3">
    <section class = "col-8 mx-auto"> 
        <%= link_to '← Categories', categories_path, :class => "btn btn-outline-dark btn-sm mb-4" %>
    </section>
</div>

app/views/categories/show.html.erb
<div class = "container">
  <section class = "col-7 mx-auto">

    <section class ="my-4">
      <h1><%= @category.title %></h1>
    </section>

    <% @category.entries.each do |entry| %>
      <div class="card my-5">
        <div class="card-body">
          <span class="badge rounded-pill bg-primary"><%= entry.category.title %></span>
          <h4 class="card-title mt-2"><%= link_to entry.title, category_entry_path(entry.category.id, entry.id), :class => "remove-link-underline"%></h4>
          <h6 class="card-subtitle mb-2 text-muted"><%= entry.date.strftime('%b %e, %Y') %></h6>
          <p class="card-text"><small><%= entry.body %></small></p>
        </div>
        <div class = "list-group d-flex flex-row justify-content-between">
          <%= link_to '', category_entry_path(entry.category.id, entry.id), :class => "bi bi-arrows-fullscreen list-group-item-action d-flex justify-content-center py-2 align-items-center remove-link-underline" %>
          <%= link_to '', edit_category_entry_path(entry.category.id, entry.id), :class => "bi bi-pencil-square list-group-item-action d-flex justify-content-center py-2 align-items-center remove-link-underline" %>
          <%= link_to '', category_entry_path(entry.category.id, entry.id), method: :delete, data: { confirm: 'Are you sure?' }, :class => "bi bi-trash-fill list-group-item-action d-flex justify-content-center py-2 align-items-center remove-link-underline" %>
        </div>
      </div>
    <% end %>

    <div class="card my-5">
      <%= link_to '+ New Entry', new_category_entry_path(@category), :class => "remove-link-underline card-body list-group-item-action text-center"%>
    </div>


    <%= link_to '← Categories', categories_path, :class => "btn btn-outline-dark btn-sm mb-4" %>

  </section>
</div>

app/views/entries/_form.html.erb
<%= form_with(model: [@category, entry], local: true) do |form| %>

  <% if entry.errors.any? %>

    <% entry.errors.each do |error| %>

    <div class="container">
      <div class="alert alert-danger alert-dismissible fade show mx-auto col-10 text-center mb-1 mt-4" role="alert">
        <%= error.full_message %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    </div>

    <% end %>

  <% end %>

  <div class ="container">
    <section class = "col-8 mx-auto">
      <div class = "card rounded-3 mt-5">
        <div class="card-body p-4 p-sm-5">

            <div class="field form-group mb-3">
              <%= form.label :title %>
              <%= form.text_field :title, :class => "form-control" %>
            </div>

            <div class="field form-group mb-3">
              <%= form.label :body %>
              <%= form.rich_text_area :body, :class => "form-control", :rows => "8" %>
            </div>

            <div class="field form-group mb-3">
              <%= form.label :date %>
              <%= form.date_select :date, {}, { class: 'form-select' }%>
            </div>

            <div class="actions d-grid mb-3 mt-4">
              <%= form.submit :class => "btn btn-primary btn-login text-uppercase fw-bold" %>
            </div>

        </div>
      </div>
    </section>
  </div>
<% end %>

app/views/entries/edit.html.erb
<%= render 'form', entry: @entry %>

<div class ="container mt-3">
    <section class = "col-8 mx-auto"> 
        <%= link_to 'Show', [@category, @entry], :class => "btn btn-outline-dark btn-sm mb-4" %>
        <%= link_to "← #{@category.title}", category_entries_path(@category), :class => "btn btn-outline-dark btn-sm mb-4" %>
    </section>
</div>

app/views/entries/index.html.erb
<div class = "container">
  <section class = "col-7 mx-auto">

    <section class ="my-4">
      <h1><%= @category.title %></h1>
    </section>

    <% @category.entries.each do |entry| %>
      <div class="card my-5">
        <div class="card-body">
          <span class="badge rounded-pill bg-primary"><%= entry.category.title %></span>
          <h4 class="card-title mt-2"><%= link_to entry.title, category_entry_path(entry.category.id, entry.id), :class => "remove-link-underline"%></h4>
          <h6 class="card-subtitle mb-2 text-muted"><%= entry.date.strftime('%b %e, %Y') %></h6>
          <p class="card-text"><small><%= entry.body %></small></p>
        </div>
        <div class = "list-group d-flex flex-row justify-content-between">
          <%= link_to '', category_entry_path(entry.category.id, entry.id), :class => "bi bi-arrows-fullscreen list-group-item-action d-flex justify-content-center py-2 align-items-center remove-link-underline" %>
          <%= link_to '', edit_category_entry_path(entry.category.id, entry.id), :class => "bi bi-pencil-square list-group-item-action d-flex justify-content-center py-2 align-items-center remove-link-underline" %>
          <%= link_to '', category_entry_path(entry.category.id, entry.id), method: :delete, data: { confirm: 'Are you sure?' }, :class => "bi bi-trash-fill list-group-item-action d-flex justify-content-center py-2 align-items-center remove-link-underline" %>
        </div>
      </div>
    <% end %>

    <div class="card my-5">
        <%= link_to '+ New Entry', new_category_entry_path(@category), :class => "remove-link-underline card-body list-group-item-action text-center"%>
    </div>


    <%= link_to '← Categories', categories_path, :class => "btn btn-outline-dark btn-sm mb-4" %>

  </section>
</div>

app/views/entries/new.html.erb
<%= render 'form', entry: @entry %>

<div class ="container mt-3">
    <section class = "col-8 mx-auto"> 
        <%= link_to "← #{@category.title}", category_entries_path(@category), :class => "btn btn-outline-dark btn-sm mb-4" %>
    </section>
</div>

app/views/entries/show.html.erb
<div class = "container">
  <section class = "col-7 mx-auto">
    <div class="card my-5">

      <div class="card-body">
        <span class="badge rounded-pill bg-primary"><%= @entry.category.title %></span>
        <h4 class="card-title mt-2"><%= @entry.title %></h4>
        <h6 class="card-subtitle mb-2 text-muted"><%= @entry.date.strftime('%b %e, %Y') %></h6>
        <p class="card-text"><small><%= @entry.body %></small></p>
      </div>

      <div class = "list-group d-flex flex-row justify-content-between">
        <%= link_to '', category_entry_path(@category, @entry), :class => "bi bi-arrows-fullscreen list-group-item-action d-flex justify-content-center py-2 align-items-center remove-link-underline" %>
        <%= link_to '', edit_category_entry_path(@category, @entry), :class => "bi bi-pencil-square list-group-item-action d-flex justify-content-center py-2 align-items-center remove-link-underline" %>
        <%= link_to '', category_entry_path(@category, @entry), method: :delete, data: { confirm: 'Are you sure?' }, :class => "bi bi-trash-fill list-group-item-action d-flex justify-content-center py-2 align-items-center remove-link-underline" %>
      </div>

    </div>

    <%= link_to "← #{@category.title}" , category_entries_path(@category), :class => "btn btn-outline-dark btn-sm mb-4" %>
    <%#= link_to '← Back to Categories', categories_path, :class => "btn btn-outline-dark btn-sm mb-4" %>

  </section>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between px-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="/categories">	✎ Records-on-Rails</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to 'Categories', categories_path, :class => "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Entries', entries_path, :class => "nav-link" %>
        </li>


        <%# <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li> %>

      </ul>

      <ul class="navbar-nav">
        <%if user_signed_in? %>

            <li class="nav-item nav-link active">
                Welcome, <%=current_user.email%>!
            </li>

            <li class="nav-item">
                <%= link_to 'Edit Profile', edit_user_registration_path, :class => "nav-link" %>
            </li>

            <li class="nav-item">
                <%= link_to 'Log Out', destroy_user_session_path, method: :delete, :class => "nav-link" %>
            </li>

        <%else%>

            <li class="nav-item">
                <%= link_to 'Sign Up', new_user_registration_path, :class => "nav-link active" %>
            </li>

            <li class="nav-item">
                <%= link_to 'Sign In', new_user_session_path, :class => "nav-link active" %>
            </li>

        <%end%>
      </ul>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
  <html lang="en">
    <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <!-- Bootstrap CSS -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

      <title>Journal App</title>

      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous" defer></script>
    </head>
    <body>
    <%= render 'layouts/navbar'%>

    <% if notice %>
    <div class="container">
      <div class="alert alert-success alert-dismissible fade show mx-auto col-10 text-center mb-1 mt-4" role="alert">
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    </div>
    <% end %>

    <% if alert %>
    <div class="container">
      <div class="alert alert-danger alert-dismissible fade show mx-auto col-10 text-center mb-1 mt-4" role="alert">
        <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>


      <!-- Option 1: Bootstrap Bundle with Popper -->
      <%# <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> %>

    </body>
</html>

app/views/user_entries/index.html.erb
<div class = "container">
  <div class = "row">
    <h1 class = "my-4">Entries</h1>

    <section class = "col-7"> 


      <% @entries.each do |entry| %>
      <div class="card mb-5">
        <div class="card-body">
          <span class="badge rounded-pill bg-primary"><%= entry.category.title %></span>
          <h4 class="card-title mt-2"><%= link_to entry.title, category_entry_path(entry.category.id, entry.id), :class => "remove-link-underline"%></h4>
          <h6 class="card-subtitle mb-2 text-muted"><%= entry.date.strftime('%b %e, %Y') %></h6>
          <p class="card-text"><small><%= entry.body %></small></p>
        </div>
        <div class = "list-group d-flex flex-row justify-content-between">
          <%= link_to '', category_entry_path(entry.category.id, entry.id), :class => "bi bi-arrows-fullscreen list-group-item-action d-flex justify-content-center py-2 align-items-center remove-link-underline" %>
          <%= link_to '', edit_category_entry_path(entry.category.id, entry.id), :class => "bi bi-pencil-square list-group-item-action d-flex justify-content-center py-2 align-items-center remove-link-underline" %>
          <%= link_to '', category_entry_path(entry.category.id, entry.id), method: :delete, data: { confirm: 'Are you sure?' }, :class => "bi bi-trash-fill list-group-item-action d-flex justify-content-center py-2 align-items-center remove-link-underline" %>
        </div>
      </div>
      <% end %>

    </section>


      <%# @categories.each do |category| %>
      <%#= link_to category.title, entries_path(:cate => category.id) %>
      <%# end %>
      <%#= link_to 'All Entries', entries_path %>

      <%#= link_to 'New Entry', new_category_entry_path(@category) %>
    <section class = "col-5">

      <div class="card w-100 mb-3">
        <%= link_to '+', new_entry_path, :class => "remove-link-underline display-4 text-secondary card-body list-group-item-action d-flex align-items-center justify-content-center"%>
      </div>


      <ul class="list-group">

        <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
          <%= link_to 'All Entries', entries_path, :class => "remove-link-underline" %>
          <span class="badge bg-primary rounded-pill"><%= current_user.entries.count%></span>
        </li>

        <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
          <%= link_to 'Today', entries_path(:day => Date.current), :class => "remove-link-underline" %>
          <span class="badge bg-primary rounded-pill"><%= current_user.entries.where(:date => Date.current).count%></span>
        </li>

        <% current_user.entries.map(&:date).uniq.each do |date| %>
          <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
            <%= link_to date.to_date.strftime('%b %e, %Y'), entries_path(:day => date), :class => "remove-link-underline" %>
            <span class="badge bg-primary rounded-pill"><%= current_user.entries.where(:date => date).count %></span>
          </li>
        <% end %>

      </ul>
    </section>

  </div>
</div>

app/views/user_entries/new.html.erb
<%= form_for @entry do |form| %>

  <% if @entry.errors.any? %>

    <% @entry.errors.each do |error| %>

    <div class="container">
      <div class="alert alert-danger alert-dismissible fade show mx-auto col-10 text-center mb-1 mt-4" role="alert">
        <%= error.full_message %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    </div>

    <% end %>

  <% end %>

  <div class ="container">
    <section class = "col-8 mx-auto">
      <div class = "card rounded-3 mt-5">
        <div class="card-body p-4 p-sm-5">

            <div class="field form-group mb-3">
              <%= form.label :title %>
              <%= form.text_field :title, :class => "form-control" %>
            </div>

            <div class="field form-group mb-3">
              <%= form.label :body %>
              <%= form.rich_text_area :body, :class => "form-control", :rows => "8" %>
            </div>

            <div class="field form-group mb-3">
              <%= form.label :date %>
              <%= form.date_select :date, {}, { class: 'form-select' }%>
            </div>

            <div class="field form-group mb-3">
              <%= form.label :category %>
              <%= form.select :category_id, current_user.categories.map{|c|[c.title, c.id]}, {}, {class: 'form-select' } %>
            </div>

            <div class="actions d-grid mb-3 mt-4">
              <%= form.submit :class => "btn btn-primary btn-login text-uppercase fw-bold" %>
            </div>

        </div>
      </div>

      <%= link_to "← Entries", entries_path, :class => "btn btn-outline-dark btn-sm my-4" %>
    </section>
  </div>
<% end %>